### ISSUE TITLE
Possible bug and a question about TextField clearing

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [mariohahn/MHValidationClass#2]
Hi,

Thanks for the cool library. I'm planning to use it in one of my apps. However I have a couple of questions.

First off, I didn't want the segmented control on top of the keyboard so I set the setShowNextAndPrevSegmentedControl to NO but it doesn't have any effect. I think this maybe a bug because when I checked the method's implementation, one of the property used in there is deprecated in iOS 7. UISegmentedControlStyleBar to be exact. Please fix it. 

Also what if I wanted to remove the entire bar on the keyboard? Is there a property for that? I checked the header file but didn't come across anything like that. I'm currently returning nil from the toolbarInit method to achieve this. If there was a property for this, that would be good.

I'm using this to validate a simple form with 2 text fields and 1 text view. Another thing I noticed is that, after posting the data, it doesn't clear out the fields. The same entered values are present even after quitting the app and launching it again! Is this done from the library? If so, is there a way to disable it?
I tried clearing the fields in the viewWillDisappear methods etc but no use. 

Thank you.

**Comment by mariohahn** [comment]
Hello, 
checkout "shouldSaveTextInput"- Now its NO by default. 
"showNextAndPrevSegmentedControl" should work now.

**Comment by Isuru-Nanayakkara** [comment]
Great! Thanks for the quick response :+1:
